### PR TITLE
fix: derive root package name from dir

### LINKED ISSUE #7: Fix root package name
The root package name is currently the default `_root`, as given by dep-graph’s DepGraphBuilder. Instead it would be nice to be able to inject this when parsing a lockfile / use the basename of the path when reading a lockfile.

### PR DESCRIPTION
**Pull request by mrackwitz**
- [x] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [x] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

Fixes #7: 
> The root package name is currently the default `_root`, as given by dep-graph’s DepGraphBuilder. Instead it would be nice to be able to inject this when parsing a lockfile / use the basename of the path when reading a lockfile.

### Notes for the reviewer

Is this the right place to do this?

### CODE REVIEW

File: lib/lockfile-parser.ts [hunk 1]
```diff
@@ -20,23 +21,32 @@ import {
...
+    rootPkgInfo?: PkgInfo
+  ): LockfileParser {
+    return new LockfileParser(yaml.safeLoad(contents), rootPkgInfo);
   }
 
+  private rootPkgInfo: PkgInfo | undefined = undefined;
   private internalData: Lockfile;
 
-  public constructor(hash: Lockfile) {
+  public constructor(hash: Lockfile, rootPkgInfo?: PkgInfo) {
```
Comment (darscan) [inline lib/lockfile-parser.ts]: TS has shorthand for this:
```ts
public constructor(hash: Lockfile, private rootPkgInfo?: PkgInfo) {
```
And then you can remove
```ts
private rootPkgInfo: PkgInfo | undefined = undefined;
```
Not everyone enjoys that syntax though though :D

Comment (mrackwitz) [reply lib/lockfile-parser.ts]: TIL, indeed not quite sold on it being better tho yet.
